### PR TITLE
Git week1 1

### PR DESCRIPTION
**Pull request by chunmeishui**
have done my homework of git week1.thanks for your feedback.

### CODE REVIEW

**Review by marta-ov — CHANGES_REQUESTED** [review]
Hey Chunmei, very good job overall! 

May i ask why did you commit the empty files and only then added the contents and committed again?

In any case, I have one last task for you: can you add one more country name to the countries-1.txt, add, commit, and push please?
And then you'll see that the pull request is updated automatically.
This is to mimic the process of implementing feedback :)

**Comment by chunmeishui** [comment]
Hi Marta, I forgot to add the conent at the first time and I add it later.I will add the country soon. Thanks .  Best RegardsChunmeiSent from Mail for Windows From: marta-ovSent: Friday, 22 October 2021 20.39To: chunmeishui/hyf-homeworkCc: chunmei; AuthorSubject: Re: [chunmeishui/hyf-homework] Git week1 1 (PR ***@***.*** requested changes on this pull request.Hey Chunmei, very good job overall!May i ask why did you commit the empty files and only then added the contents and committed again?In any case, I have one last task for you: can you add one more country name to the countries-1.txt, add, commit, and push please?And then you'll see that the pull request is updated automatically.This is to mimic the process of implementing feedback :)—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chunmeishui** [comment]
Hi Marta, I did that.Pls have a look. Thanks for your feedback.  RegardsChunmei Sent from Mail for Windows From: marta-ovSent: Friday, 22 October 2021 20.39To: chunmeishui/hyf-homeworkCc: chunmei; AuthorSubject: Re: [chunmeishui/hyf-homework] Git week1 1 (PR ***@***.*** requested changes on this pull request.Hey Chunmei, very good job overall!May i ask why did you commit the empty files and only then added the contents and committed again?In any case, I have one last task for you: can you add one more country name to the countries-1.txt, add, commit, and push please?And then you'll see that the pull request is updated automatically.This is to mimic the process of implementing feedback :)—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Review by marta-ov — APPROVED** [review]
It's great! :D
You can now merge your PR :D

**Comment by chunmeishui** [comment]
Okay Thanks a lot. :D Sent from Mail for Windows From: marta-ovSent: Tuesday, 26 October 2021 10.00To: chunmeishui/hyf-homeworkCc: chunmei; AuthorSubject: Re: [chunmeishui/hyf-homework] Git week1 1 (PR ***@***.*** approved this pull request.It's great! :DYou can now merge your PR :D—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chunmeishui** [comment]
finished homework of git week1

**Pull request merged**
